### ISSUE TITLE
What is the location that we get

### ISSUE THREAD

**Issue by raddatzk** [flutter/flutter_clock#9]
I would like to use the current location, but the the location provided in the ClockModel says "Mountain View, CA". Am I allowed to transform the location to coordinates via the Play Services?

**Comment by wheel1992** [comment]
Thought that the official website has indicated the following requirements

=====
...

**Design and data notes:**
The ClockModel API with mock data is provided to you. Using this API is optional, but it provides system information such as the brightness mode, weather, and time format.
- The clock design should use landscape mode, with a 5:3 aspect ratio.
- You may use Material Design icons.
- All other assets, fonts, icons, images, and so on should be your own, or licensed under a BSD-3, or OFL license (for fonts).
- Your clock should not:
  - Have user interaction (such as tapping, gestures, dragging, mouse, keyboard, and so on).
  - Play audio, including an alarm.
  - **Make network requests.**
  - Collect data in violation of applicable laws (including privacy laws).
  - Contain copyrighted or trademarked content.

...

**Comment by raddatzk** [comment]
Yes I already read this, but I hoped it will be okay to call the Play Services, as this is not some ridiculous-api:1.7

**Comment by maryx** [comment]
The location is a String. Feel free to go into model.dart and hardcode it to something else while you develop (but revert and submit the original model with your project).

Because it is a String and doesn't have validation, feel free to make your `location` a String coordinate (e.g. `'(12.345678, -12.3456789)'`). Make a note of that in your submission (maybe add some example strings to try) if the UI behaves differently based on the `location` String.

You may not use Play Services.
